### ISSUE TITLE
Inconsistent logic with parameter shift in evaluator/haspi/eb.CenterFreq

### ISSUE THREAD

**Issue by groadabike** [claritychallenge/clarity#105]
The EarModel in evaluator/haspi/eb computes the center frequency using shift = 0.02

https://github.com/claritychallenge/clarity/blob/94e39d43a304f2b13e33278451fe17c1860f4a2f/clarity/evaluator/haspi/eb.py#L70-L75

However, the function CenterFreq in evaluator/haspi/eb forces the parameter to be None to keep consistency with Matlab

https://github.com/claritychallenge/clarity/blob/94e39d43a304f2b13e33278451fe17c1860f4a2f/clarity/evaluator/haspi/eb.py#L180-L233

What is the point of setting shift in center freq if it is never used? 
Setting the value in the Ear Model gives the impression that a shift is applied, won't that confuse people while reading the code? 

What would be the best way to clean this part of the code?
1- Changing shift to None in EarModel?
2- Removing shift parameter from CenterFreq?
3- Removing the `shift=None` statement in CenterFreq?

**Comment by ns-rse** [comment]
Presumably there may be instances where it is desirable to have a shift applied.

If that is the case then my approach would be to add a `shift` parameter to the `EarModel` function...

```python
def EarModel(x, xsamp, y, ysamp, HL, itype, Level1, shift: float=None):
```

...line [72](https://github.com/claritychallenge/clarity/blob/94e39d43a304f2b13e33278451fe17c1860f4a2f/clarity/evaluator/haspi/eb.py#L72) where `shift = 0.02` can then be removed and whatever value `EarModel(shift = XX)` is called with will get passed in the next line [73](https://github.com/claritychallenge/clarity/blob/94e39d43a304f2b13e33278451fe17c1860f4a2f/clarity/evaluator/haspi/eb.py#L73) (`cfreq1 = CenterFreq(nchan, shift)`).

In the `CenterFreq()` function definition the default is already `shift=None` and so if the above change is made to `EarModel()` then the value will cascade through and the current line [208](https://github.com/claritychallenge/clarity/blob/94e39d43a304f2b13e33278451fe17c1860f4a2f/clarity/evaluator/haspi/eb.py#L208) can be removed.

That way things should just cascade through, with the default being `None`.

I hope that makes sense, and apologies I can't comment on what the value should actually be.

**Comment by groadabike** [comment]
@jonbarker68 , thank you so much for the clarification.
Let's wait for the #85 to be merged before doing changes in haspi.eb
Just to play safe
