### ISSUE TITLE
Errors due different devices when running Test locally.

### ISSUE THREAD

**Issue by groadabike** [claritychallenge/clarity#106]
When running `pytest --cov=clarity` locally on my laptop, some of the tests that use Pytorch fail due to different devices.
Note that I do have a GPU on my laptop.

The output error is:

> FAILED tests/regression/test_enhancers.py::test_dsp_filter - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argum...
FAILED tests/regression/test_mc_conv_tasnet.py::test_convtasnet - RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

Maybe we need to be more explicit about the devices used in the test. We could create a util.device file, similar as proposed by @ns-rse in https://github.com/claritychallenge/clarity/issues/97#issuecomment-1313549828

**Comment by ns-rse** [comment]
I have noticed this, currently there are statements such as...

```
self.device = "cuda" if torc.cuda.is_available() else "cpu"
```

I think making it optional as to whether `.cuda()` is used might be prudent and so...

```
    def __init__(
        self,
        ...
        device: str=None
    ):
    ...
    if device is None:
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
    else:
        self.device = device
```

That way in the tests we can explicitly force all instantiations to be `device="cpu"` which goes above and beyond @TuZehai recent modifications to the tests to force `x.cpu()` in `tests/regression/test_predictors.py` (see #101) (and on reflection the `if torch.cuda.is_available()` can now be removed from both of those tests as they are being forced to use `.cpu()`).

**Comment by TuZehai** [comment]
Oooops, I thought the latest version should have fixed this... Could you try to have another try?

**Comment by ns-rse** [comment]
I'm happy to implement the above logic across the modules that use `torch`.

From #97 these are...

```
❱ grep "cuda\(\)" clarity -R -l
clarity/enhancer/dnn/mc_conv_tasnet.py
clarity/enhancer/dsp/filter.py
clarity/predictor/torch_msbg.py
```

**Comment by TuZehai** [comment]
Thanks Neil, forcing everything on `cpu` should work.
