### ISSUE TITLE
Source Separation

### ISSUE THREAD

**Issue by groadabike** [claritychallenge/clarity#115]

**Comment by groadabike** [comment]
@jonbarker68 , @TuZehai , @ns-rse 
I will start the implementation of a function to apply a source separation to a stereo/mono song.
In terms of the repo directory tree, where will you include it?

- The data directory seems too Challenge specific.
- This would be a simple utility function to call when is need it, so perhaps a "utils" directory at the root level.

This will be a Cadenza-specific function but I don't think we need to separate it some the rest of the code, just to make it clear in the  docstring

**Comment by groadabike** [comment]
@jonbarker68 , @TuZehai , @ns-rse

**Comment by ns-rse** [comment]
Hi @groadabike 

This sounds good, I presume its [Music Source Separation with Hybrid Demucs — Torchaudio 0.13.0 documentation](https://pytorch.org/audio/stable/tutorials/hybrid_demucs_tutorial.html) that you are referring to?

This is my ignorance about how things are structured but would it be a tool others use for separating audio or something used in assessing submissions to the challenge which have sought to clean up audio tracks?

As to location `utils/source_separation.py` would be fine for now. Sometimes though `utils/` modules can end up being a catch all area when there is a more logical grouping to be had for components that have ended up there.

Perhaps as this is focused on the music orientated challenges it might suggest `music/source_separation.py` as a module/sub-module location for it to reside? I'm not too sure though so defer to others :shrug:

**Comment by groadabike** [comment]
I don't really like the idea to add it in the baseline directory. 
What happens if we decide to use it again in challenge 2?

**Comment by TuZehai** [comment]
I am not quite sure about the purpose. If it is a tool for generating the challenge data, you could probably put the tool in `data`, and put the code using the tool in let's say `recipes/cadenza1/data_preparation`. This is what I did for `cec2`

**Comment by ns-rse** [comment]
Ok so perhaps something as simple as `audio/source_separation.py` would be generic and still meaningful (or "pythonic" as some people term it).

**Comment by groadabike** [comment]
Tbh, I don't really like the name `audio` for a directory in this case. To me, a dir name `audio` contains audio wavs.

We may need to define a meaningful directory tree. not only for the source_separation but any new functionalities. 
Also, I don't think we should organise based on **speech** or **music** as many functionalities can be used in both cases.

One good reference of directory names can be Asteroid.  
For example, in Asteroid, they have only one `data` dir to save the datasets. In contrast, we have 2 dirs with similar names which can be confusing: `data` and `dataset`
Perhaps, and following Asteroid, the content from `data` can be split and moved into:
- scene -> for scene generators
- processing -> for the HOA 

In this case, the source_separation module should be placed in `processing`.
Therefore, the root in clarity would look as:
- data
- engine
- enhancer
- evaluator
- predictor
- processing

**Comment by ns-rse** [comment]
Fair enough I don't have strong feelings on it either way but my perspective is that  this is a Python project directories under `clarity` represent modules, audio wavs I would consider to be data and would sit outside of the `clarity` directory. There can of course still be `data` modules for processing data under `clarity/data`.

I think it would be prudent to sort out a structure though as it will aid in separating common modules from challenge specific ones.
