### ISSUE TITLE
[FEATURE] Print cpuinfo in test.  

### ISSUE THREAD

**Issue by groadabike** [claritychallenge/clarity#129]
Printing cpuinfo may help to understand better why some tests fail seemingly randomly.
- name: Server Architecture
      run: |
        python -c "import numpy as np; print(np.show_config())"
        cat  /proc/cpuinfo | grep "model name"

**Comment by ns-rse** [comment]
#135 introduces tests conditional on architecture and retains printing out the CPU for future reference/debugging.
