### ISSUE TITLE
Improve decompose_signal() in recipes/cad1/task1/baseline/enhance.py

### ISSUE THREAD

**Issue by ns-rse** [claritychallenge/clarity#198]
Currently the `decompose_signal()` function (starting at [line 142](https://github.com/claritychallenge/clarity/blob/2583162ff90c3fb05eba788acd8f5b9e2a2f49d4/recipes/cad1/task1/baseline/enhance.py#L142)) of `recipes/cad1/task1/baseline/enhance.py` includes the arguments `left_audiogram` and `right_audiogram`. These arguments are not used in the function though and `pylint` raises error [`unused-argument`](https://pylint.pycqa.org/en/latest/user_guide/messages/warning/unused-argument.html) error.

The reason they are there [is](https://github.com/claritychallenge/clarity/pull/193/files#r1124119738)...

> This was intentionally left in this way. The idea is to show participants that even thou the baseline is not using the audiograms, they can modify the function and take use of them.

I think it might be possible to make life a little easier for users though and have two possible suggestions...

## Allow options and optionally replace `signal`

If a user want to process left or right audograms you could...

```python
    if left_audiogram is not None:
        signal = left_audiogram
    elif right_audiogram is not None:
        signal = right_audiogram
    elif left_audiogram is not None and right_audiogram is not None:
        Exception("Please specify on one of left_audiogram or right_audiogram")
```

...and note in the docstring that if either `left_audiogram` or `right_audiogram` is specified it will replace `signal`.

## Remove the options and improve the docstring

Alternatively just remove the  `left_audiogram` and `right_audiogram` options and improve the docstring to reflect the fact that `signal` can be a combined channel or a single decomposed channel of either left or right audio.

Either of these would I think make it easier for participants to use the function with either the baseline (`signal`) or the `left_audopgram` or `right_audiogram` without having to modify it. Which is most appropriate I couldn't say as I'm not too familiar with how it might fit or be used in workflow and so defer the decision to others.

**Comment by groadabike** [comment]
Thank you @ns-rse 

How about if we add the `**kwargs` parameter in  `decompose_signal()` to enable other parameters?
Is there any type hint we can use?

**Comment by ns-rse** [comment]
You could add a `**kwargs` but how would they actually be used?

The reason `pylint` complains about a `unused-argument` is because neither of the variables `left_audiogram` nor `right_audiogram` are actually used within the `decompose_signal()` function. Allowing them via `**kwargs` won't change that situation.

If the aim is to allow `decompose_signal()` to work with both a dual-channel signal (the default argument of `signal` which is an `np.ndarray`) or a single-channel signal (whether that is `left_audiogram` or `right_audiogram` both of which are `np.ndarray`) then I would personally got with the second option of clarifying the `docstring` and allowing users to choose which they pass into the function.

It is of course quite possible I'm not understanding the purpose of `decompose_signal()` and how the different options might work. In that regard if you've time to sketch out how you envisage participants might use the function as it is currently written to work with `left_audiogram`/`right_audiogram` I might have different suggestions but currently I think it would require them to change the reference to `signal` within the function. In turn they would then need to re-install the package and if they've done so via PyPI (i.e. `pip install` method) that isn't going to work, they would then have to `git clone` the repository and `pip install -e .` the package then make the changes to the function. This is possible but its a lot of faff just to change which array is passed into a function when a change to a docstring can make it clear to the user that it will accept many arrays and its up to them to choose which to pass in.

**Comment by groadabike** [comment]
Hi @ns-rse, 
So sorry, I didn't realise that I didn't explain what the left and right audiograms are.
They are not audio signals, instead, they are a list (cast in a np.ndarrray) with 8 values corresponding to the hearing loss at certain frequencies.

Participants could pass the audiograms together with the audio signal to the separation model.

**Comment by ns-rse** [comment]
Thanks for taking the time to explain that @jonbarker68 massively improved my understanding of how recipes are structured and intended to be used.
