### ISSUE TITLE
Question about the CEC1 baseline system

### ISSUE THREAD

**Issue by Chengwei-Ouyang** [claritychallenge/clarity#2]
When I run the enhance.py and evaluate.py in CEC1 baseline folder, I get different results comparing with the sii.csv in the repo. Do you have any advice on this problem? Thanks for your help!
![image](https://user-images.githubusercontent.com/70736875/166261270-12978f27-d872-405c-9759-83bc05e6fd7b.png)

**Comment by TuZehai** [comment]
Hi,

I am not sure what leads to the difference. We are currently using OpenMHA version 4.12.0.

Here is the md5sum result for the enhanced S06001_L0008_HA-output.wav: 1b8b7dc45413fdc339c59181d20541c4

Could you please check you get the same enhanced signal for S06001_L0008?

Thanks

**Comment by Chengwei-Ouyang** [comment]
Thanks for you reply! I got different md5sum result for the enhanced S06001_L0008_HA-output.wav and I'm using OpenMHA version 4.17.0. I'm going to downgrade OpenMHA to 4.12.0 and retry it.
