### ISSUE TITLE
Speed up test suite by reducing length of samples

### ISSUE THREAD

**Issue by ns-rse** [claritychallenge/clarity#203]
Currently the test suite takes quite a while to run in full. This could be sped up by reducing the size of samples that are processed across the test suite.

Perhaps setting them up as fixtures in `tests/conftest.py` would be a sensible approach.

**Comment by jonbarker68** [comment]
> pytest --durations 10
27.15s call     tests/recipes/cad1/task1/test_evaluate.py::test_evaluate_song_listener[punk_is_not_dead-my_music_listener-config0-test-listener_audiograms0-expected_results0]
15.09s call     tests/regression/test_full_CEC2_pipeline.py::test_full_cec2_pipeline
8.68s call     tests/regression/test_mc_conv_tasnet.py::test_convtasnet
7.05s call     tests/evaluator/haaqi/test_haaqi.py::test_haaqi_v1
6.65s call     tests/evaluator/haaqi/test_haaqi.py::test_compute_haaqi
6.50s call     tests/evaluator/hasqi/test_hasqi.py::test_hasqi_v2
3.02s call     tests/regression/test_full_CEC1_pipeline.py::test_full_CEC1_pipeline
2.22s call     tests/regression/test_predictors.py::test_torch_msbg_stoi_non_xeon_e5_2673_cpu
0.83s call     tests/data/test_HOA_tools_cec2.py::test_V[0-2-2--0.02607000059684761]
0.60s call     tests/recipes/cad1/task1/test_enhance.py::test_decompose_signal

**Comment by jonbarker68** [comment]
closed by PR #212
