### ISSUE TITLE
Adding the pyupgrade precommit hook

### ISSUE THREAD

**Issue by jonbarker68** [claritychallenge/clarity#244]
We can very cheaply improve the code base by using [pyupgrade](https://github.com/asottile/pyupgrade). This will automatically check and modernise Python code while staying compatible with some given minimum version.   eg. to make code as modern as possible while still supporting Python 3.7 we just need to run.

```
pyupgrade --py37-plus
```

It can be run by pre-commit and is very fast. It makes fixes automatically so there is no real downside.

A quick test is showing that most changes will be removing "r" when opening files in read mode - which is now a default and considered bad style to include. But also we can modernise a lot of type hints. pyupgrade will do this for us if just add 

```
from __future__ import annotations
```

**Comment by ns-rse** [comment]
Wow, now that is a very cool tool and to be able to leverage it via `pre-commit` is a massive bonus. Its like :magic_wand: :mage:

Will definitely be applying this to other projects, really useful to know about, thanks @jonbarker68 :+1:
