### ISSUE TITLE
Consistent use of pytest.approx in tests

### ISSUE THREAD

**Issue by jonbarker68** [claritychallenge/clarity#250]
We have a lot of tests that compare floating point results and are hard to reproduce on different platforms.

I think we should confine these to tests/regression and use pytest.approx in all other test modules.

This will mean that we can have a set of fast tests that are not fussy about CPU architecture that can run with,

pytest --ignore tests/regression

And we can keep the super-sensitive longer regression tests which run with GitHub actions when we merge. 

This will make it easier to test during development,  (e.g. when developing on a mac, the test suite is currently throwing lots of errors due to differences in the 8th or 9th significant fugue)

**Comment by ns-rse** [comment]
Files to check...

+ [ ] `./test_scene_renderer_cec1.py`
+ [ ] `./recipes/cpc2/__init__.py`
+ [ ] `./recipes/cpc2/test_predict.py`
+ [ ] `./recipes/cpc2/test_evaluate.py`
+ [ ] `./recipes/cpc2/test_compute_haspi.py`
+ [ ] `./recipes/cad1/task2/__init__.py`
+ [ ] `./recipes/cad1/task2/test_audio_manager.py`
+ [ ] `./recipes/cad1/task2/test_build_scene_metadata.py`
+ [ ] `./recipes/cad1/task2/test_enhance.py`
+ [ ] `./recipes/cad1/task2/test_baseline_utils.py`
+ [ ] `./recipes/cad1/task1/__init__.py`
+ [ ] `./recipes/cad1/task1/test_enhance.py`
+ [ ] `./recipes/cad1/task1/test_evaluate.py`
+ [ ] `./data/test_HOA_tools_cec2.py`
+ [ ] `./data/test_utils.py`
+ [ ] `./test_import.py`
+ [ ] `./test_scene_renderer_cec2.py`
+ [ ] `./enhancer/test_nalr.py`
+ [ ] `./test_compressor.py`
+ [ ] `./conftest.py`
+ [ ] `./utils/test_file_io.py`
+ [ ] `./utils/car_noise_simulator/test_carnoise_signal_generator.py`
+ [ ] `./utils/car_noise_simulator/test_carnoise_parameter_generator.py`
+ [ ] `./utils/test_signal_processing.py`
+ [ ] `./evaluator/haaqi/test_haaqi.py`
+ [ ] `./evaluator/haspi/test_eb.py`
+ [ ] `./evaluator/haspi/test_ebm.py`
+ [ ] `./evaluator/haspi/test_haspi.py`
+ [ ] `./evaluator/haspi/test_ip.py`
+ [ ] `./evaluator/hasqi/test_hasqi.py`
+ [ ] `./evaluator/mbstoi/test_mbstoi_utils.py`
+ [ ] `./evaluator/mbstoi/test_mbstoi.py`
+ [ ] `./evaluator/msbg/test_smearing.py`
+ [ ] `./evaluator/msbg/test_msbg.py`
+ [ ] `./evaluator/msbg/test_cochlear.py`
+ [ ] `./evaluator/msbg/test_audiogram.py`
+ [ ] `./evaluator/msbg/test_msbg_utils.py`
+ [ ] `./regression/test_mc_conv_tasnet.py`
+ [ ] `./regression/test_evaluators_msbg.py`
+ [ ] `./regression/test_enhancers.py`
+ [ ] `./regression/test_CEC2_scene_builder.py`
+ [ ] `./regression/test_data_HOA_tools_cec2.py`
+ [ ] `./regression/test_engine_losses.py`
+ [ ] `./regression/eb.py`
+ [ ] `./regression/test_predictors.py`
+ [ ] `./regression/test_full_CEC2_pipeline.py`
+ [ ] `./regression/test_full_CEC1_pipeline.py`

**Comment by jonbarker68** [comment]
One's in evaluator will be OK as I started using approx consistently when adding those.  👍
