### ISSUE TITLE
Audiograms - this exists as an audiogram class but is not being used consistently in the code base

### ISSUE THREAD

**Issue by groadabike** [claritychallenge/clarity#277]

**Comment by groadabike** [comment]
@jonbarker68,
 
Is the `clarity/enhancer/gha/` the best place for the class `Audiograms`?
If we want to use it consistently in Cadenza/Clarity recipes, it shouldn't be part of the `enhancer/gha` as it is not only for `camfit`.

I feel that this class fit better in a different location like `clarity/utils/commons` or `clarity/commons` or similar.

What do you think?

**Comment by jonbarker68** [comment]
> @jonbarker68,
> 
> Is the `clarity/enhancer/gha/` the best place for the class `Audiograms`? If we want to use it consistently in Cadenza/Clarity recipes, it shouldn't be part of the `enhancer/gha` as it is not only for `camfit`.
> 
> I feel that this class fit better in a different location like `clarity/utils/commons` or `clarity/commons` or similar.
> 
> What do you think?

I agree.  It's actually defined in a couple of places enhancer/gha and evaluator/msbg. The plan will be make a single class that they both use and that is place somewhere more obvious in the module hierarchy. 

It needs a bit of careful thought though: some functions are binaural and expect an audiometric thresholds for a left and right ear, others are monaural.  The simplest option would be that audiograms are always for one ear, and that binarual functions need a pair of audiogram objects. But that doesn't capture that binaural audiograms have a shared frequency axis but it would keep things simple and in principle you could have different frequency measurements made in each ear. 

You'll see this issue quite clearly if you compare the current enhancer/gha and evaluator/msbg designs.
