### ISSUE TITLE
Add precomputations to HAAQI

### ISSUE THREAD

**Issue by groadabike** [claritychallenge/clarity#363]
There are two banches working with HAAQI to improve the metric. However, after several analysis, I realised that many of the slowest parts can be improved by precomputing values. These values correspond computations that are not related to the signals. Additionally, as HAAQI works at 24000 Hz, many of the computations that depend on the sample rate can also be precomputed:

1. Filter coefficients in `eb.env_compress_basilar_membrane`: 
     Depends on a constant (flp = 800) and sample rate

2. Filter coefficients in `eb.middle_ear` 
     Depends on sample rate 

3. Group delay vector in `eb.group_delay_compensate`
     These are constant

4. `Sin` and `Cos` in `eb.gammatone_bandwidth_demodulation`
     This is a recursive function (every 300 samples) that depends on the length of the audio signal (i.e., 24000 samples per second of audio) and the sample rate. However, considering values to the 10th decimal place, the function is periodic. 

![image](https://github.com/claritychallenge/clarity/assets/17277802/e3cebbf3-3a7c-4cf1-82b2-f5c9ca0cd330)

![image](https://github.com/claritychallenge/clarity/assets/17277802/4081a32f-ee16-4828-b041-5bc912493e96)

**Comment by jonbarker68** [comment]
Yes. This is all true. The solution is probably to make an OOP version of these metrics.  If you look at the MSBG code you will see that there is an Ear class which has a Cochlea object. A set_audiogram method will build a new Cochlea for the Ear. This allows all the precomputation to be done in the object constructors so that the Ear's process() method doesn't repeat the parts that are signal independent.  It would be great if the Kates' models were all rewritten in this style.

Note, also that the MSBG code has its own implementation of a gammatone filterbank.  See gammatome_filterbank in cochlea.py.  This looks like the cascaded filter implementation. Here it is just a loop of lfilter commands, so no use of any njit code.  This would probably be much faster if we could show that it gave similar results. But I haven't benchmarked it.

**Comment by groadabike** [comment]
I checked the periodicity and found that some are not "perfect" I mean, you can find the period (no more than 300 samples) However, the values for some bands are the same in each period with variation in the 15th decimal place but, for other bands, the variations are in the 3rd or 4th decimal place. repeating the first period resulted in a reduction of 0.02 HAAQI in the example I was running from 0.12 to 0.10.

Regarding refactoring HAAQI, there are many computations that can be done in the constructor and others that could be saved:

1. There are many constants and 3 or 4 filters' numerator and denominator that depends only on sample rate that can be precomputed and saved as constant in the class.

2. The `sin` and `cos` for the gammatone depends only on the length of the signal, so they could be computed only the first time the metric is called. Pre-saving this computation for a specific max length can be another option but, may increase the clarity package size. We could add this as part of the constructor and compute only if precomputations are not given.     

3. Profiling the original HAAQI, one third of the computation are the number of correlations.

**Comment by groadabike** [comment]
HAAQI's Ear model is hard to separate as the MSGB does.
The main issue is an alignment step that run for all the bands (32 times)


https://github.com/claritychallenge/clarity/blob/6b98a25bb13e75458fb58fdc2b76be0059a5a9cb/clarity/evaluator/haspi/eb.py#L240-L248


In this part of the Ear model, the `processed signal` is aligned with the `reference signal`. This makes this step of the process of the `reference signal` a requirement for properly process the `processed signal`.

As we can't really make the ear model independent of the signal we could have the following structure.
Note, from now on, I will called the `processed signal` as `enhanced signal` to avoid confusions

EarModel Class:
- `__init__`: In the constructor we can compute all the parameters that depends on frequency sample to avoid repetitions.
- `set_audiogram`: Here we can compute parameters that depend on audiogram but are common for `reference` and `enhanced`
- `process_reference`:  Here we compute the reference ear model.  
- `process_enhanced`:  Here we compute the processed ear model. We can condition this method to the execution of `process_reference`

For me, it is not an ideal structure but I can't think in another. @jonbarker68, any suggestions?

**Comment by groadabike** [comment]
Analysing the ear model, it has 2 functions using almost all the execution time: `envelope_align` and `gammatone_basilar_membrane`.

The next figure show the execution time for 15-second signals. The total execution takes 8.3 seconds.
![image](https://github.com/claritychallenge/clarity/assets/17277802/605659e1-abcc-4672-9609-5f5de84ff804)

- The  `envelope_align` takes 2.6 seconds. However, it may not be necessary to use the whole signal for the alignment, maybe we can select one second to find the delay, which it is not expected to be more then 200 samples 
- The `gammatone_basilar_membrane` is the green box next to `envelope_align` and it takes 1.7 seconds to execute.

**Comment by groadabike** [comment]
These precomputations don't improve the time take by the metric and add complexity to it.
Closing the issue
