### ISSUE TITLE
Unnecessary log

### ISSUE THREAD

**Issue by groadabike** [claritychallenge/clarity#387]
Hi @jonbarker68,

In the camfit gaintable implementation in Clarity, the function is logging the noiselevel every single time the gain tables are generated. I think this is an unnecessary log information and a bit noisy. 
Or, there is a reason for it and we can't remove it?

https://github.com/claritychallenge/clarity/blob/c20c317a27adee88679cdc7125b8d765af65ffbd/clarity/enhancer/gha/gainrule_camfit.py#L482-L484

**Comment by jonbarker68** [comment]
Sure it can be removed. I expect it was there originally for debugging purposes. Could perhaps change the level to debug?
