### ISSUE TITLE
Question about amplification model in e009_sheffield

### ISSUE THREAD

**Issue by Chengwei-Ouyang** [claritychallenge/clarity#4]
I notice that the amplification model (AudiometricFIR) doesn't take audiogram as inputs, so it seems that I have to train an individual amplification model for each listener, which is weird for me. Could you give me some suggestions on how to generalize the amplification model or I have to train 100 individual models for 100 listeners in CEC1 challenge? Thank you!

**Comment by TuZehai** [comment]
Hi,

That is indeed the case for the E009 system, i.e. one individual amplification model for each listener. One method for generalisation could be: first do some clustering according to audiograms, say mild, moderate, and severe; then train an 'average' model for the average audiogram of each cluster; finally finetune based on the average model.

The CEC1 challenge has ended. You are very welcome to participate the CEC2 challenge, which has just been released, please see https://claritychallenge.github.io/clarity_CC_doc/.

Thanks

**Comment by Chengwei-Ouyang** [comment]
Thanks for you reply! I have already decided to participate the CEC2 challenge, and I want to try my model in CEC1 challenge firstly and get a baseline results.
