### ISSUE TITLE
[FEATURE] Integrate pylint into development pipeline

### ISSUE THREAD

**Issue by ns-rse** [claritychallenge/clarity#42]
**Is your feature request related to a problem? Please describe.**

No problem, but as part of improving the code base we can incorporate [pylint](https://pylint.pycqa.org/en/latest/) into the Continuous Integration/Development (CI/CD) pipeline as part of `lint.yml` via [pre-commit](https://pre-commit.com/).

**Describe the solution you'd like**

Code should be linted with `pylint` prior to commits (using [pre-commit](https://pre-commit.com/)).

However, first all code needs linting (see separate issue #).

**Comment by jonbarker68** [comment]
This is complete. Think I accidentally reopened it by adding it to the 0.2.0 milestone? Closing again.
