### ISSUE TITLE
Increased regression test code coverage

### ISSUE THREAD

**Issue by jonbarker68** [claritychallenge/clarity#48]
Current regression test only covers CEC2 baseline, i.e. signal mixing, NALR and haspi. Need a more thorough set of tests covering CEC1, CPC1 and CEC2 code so that later refactoring can be performed securely.

**Comment by ns-rse** [comment]
After discussion the following modules will be worked on by @jwillbailey and @TuZehai 

|  Module               | Addressed by |
|:----------------------|:-------------|
| `clarity/predictor/*` | @TuZehai     |
| `clarity/engine/*`    | @TuZehai     |
| `clarity/data/*`      | @jwillbailey |
| `clarity/enhancer/*`  | @jwillbailey |
