### ISSUE TITLE
sample delay between left and right channel does not seem to match the metadata

### ISSUE THREAD

**Issue by popcornell** [claritychallenge/clarity#6]
Hi everyone, 

first let me thank you for organizing this great challenge ! I am excited to participate.
 
I am looking at the data right now and in particular I am checking the delay (in terms of samples) between the left and right channels at each mic. Now it is not an easy task with Audacity to do this and I may be wrong. 
But it seems to me that the delay for e.g S06001 in dev set is way off from what it should be from the metadata. 
I count around 19-20 samples of delay when looking at S06001_target_anechoic_CH1.wav:

![Screenshot_20220522_175539](https://user-images.githubusercontent.com/18726713/169717623-c2299d95-0a98-449e-be49-ebeaed77b2d7.png)

According to the metadata the head rotation should be: 
```json
"listener": {
      "rotation": [
        {
          "sample": 90952.7142,
          "angle": -125.8235
        },
        {
          "sample": 100246.7142,
          "angle": -112.0054
        }
```

And so I would expect the delay to be much less. Probably I am doing something wrong but just in case, maybe it could be useful if you can double check. 

 ~~Also one thing I expected is that regarding the anechoic response the two channels should be equal except for a small delay and a gain factor (including inverted polarity). But this is not the case. Is it because the scenes are generated via higher order ambisonics RIRs and then the actual array is approximated from such HOA rirs ?~~
 EDIT: I think I've figured out, it should be the head related impulse response. 
 This makes difficult to check the delay manually on audacity. So it is very possible I am over-estimating it.

**Comment by TuZehai** [comment]
Hi,

![Screenshot from 2022-05-23 16-46-37](https://user-images.githubusercontent.com/29578522/169857745-e42d40ac-009f-4714-807a-ecdaa16df1f1.png)

Thanks for noticing the issue. I think the data you are checking is probably wrong (i.e. from the v1.0). We updated the data to v1.1 several weeks ago, and figure shows the S06001_target_anechoic_CH1.wav from the v1.1 (the download link is https://mab.to/zU7TS8jJelkoD ). The delay should be much more reasonable.

The head rotation simply describes the listener's head rotation movement, therefore should not necessarily reflect the delay. Please see https://claritychallenge.github.io/clarity_CC_doc/docs/cec2/data/cec2_data#d8-scene-metadata

Sorry for the confusion and trouble about the data...

**Comment by jwillbailey** [comment]
Hi Samuele,

As per your edit, yes the delay between right and left channels you see there is due to the HRTF. This delay is determined by the interaural distance of the particular HRTF used and the angle of the source. 

The angle of the listener head relative to the target source synchrionised to the audio is given in the files appended "_HR.wav" in the scenes audio folder. Although this is saved as audio data, it is actually head rotation information given in degrees and sampled at 44100hz.

The metadata you quote in your post actually refers to when rotations begin and end (given in samples, not time) and the start and finish look directions in degrees.

Hope this helps

Will

**Comment by popcornell** [comment]
Hi @jwillbailey, @TuZehai, 

I downloaded the new data and the delay seems consistent with initial looking direction. 
We can close this issue.
