### ISSUE TITLE
Code generating NumbaPendingDeprecationWarning

### ISSUE THREAD

**Issue by jonbarker68** [claritychallenge/clarity#67]
Numba code is generating a warning about use of a deprecated type

`Encountered the use of a type that is scheduled for deprecation: type 'reflected list'`

This needs fixing to prevent errors arising when newer versions of numba are released.

Information on how to fix can be found [here](https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types).

**Comment by ns-rse** [comment]
Closed by #68
