### ISSUE TITLE
Unit tests for evaluator module

### ISSUE THREAD

**Issue by ns-rse** [claritychallenge/clarity#85]
Develop unit tests for the data module (see #80 for overview).

Specific modules within `evaluator` are...

- [x] `evaluator/haspi`
- [x] `evaluator/haspi/eb.py`
- [x] `evaluator/haspi/ebm.py`
- [x] `evaluator/haspi/ip.py`
- [x] `evaluator/haspi/haspi.py`
- [x] `evaluator/hasqi/hasqi.py`
- [x] `evaluator/haaqi/haaqi.py`
- [x] `evaluator/mbstoi`
- [x] `evaluator/mbstoi/mbstoi.py` 
- [x] `evaluator/mbstoi/mbstoi_utils.py` 
- [x] `evaluator/msbg`
- [x] `evaluator/msbg/audiogram.py` No change required.
- [x] `evaluator/msbg/cochlea.py`
- [x] `evaluator/msbg/msbg.py`
- [x] `evaluator/msbg/msbg_utils.py`
- [x] `evaluator/msbg/smearing.py`

**Comment by ns-rse** [comment]
* [x] evaluator/msbg/masbg.py
* [x] evaluator/msbg/masbg_utils.py
See #119

**Comment by jonbarker68** [comment]
This was accidentally closed by the merge of #237 - the MSBG components still need completing
