### ISSUE TITLE
Questions on latency, use of external data and ch0

### ISSUE THREAD

**Issue by hyli666** [claritychallenge/clarity#9]
Hi, Thanks so much for organizing the challenge, and providing detailed docuement.
I am very interested on it and have a few questions below:

1). There is 5-ms latency limitation for the enhancement model. Will the frame length be counted in latency? I read some papers in CEC1. One team [(paper)](https://claritychallenge.github.io/clarity2021-workshop/papers/Clarity_2021_CEC1_paper_final_chen.pdf) used a 32-ms window. I am wondering if this long window size (beyond 5ms) is allowed in CEC2?

2). Regarding on the use of external data. I plan to use external noisy data to train a more robust denoising module. If I do this, seems I have to submit two systems, with using and without using external data. If I plan to submit entries for HASPI and listening tests, respectively, does this mean I need to submit four entries (2 tests X 2 data uses) in total?

3). Just one thing to confirm: Was ch0 (eardrum) signal also included in the release of CEC1 dataset? 
I found ch0 was included in CEC1 data (written in [document](https://claritychallenge.github.io/clarity_CEC1_doc/docs/cec1_data)), but seems many submissions only used 6 channels (ch1~3 pairs), and no team used ch0. So just curious on it.

Again, thank you so much for your work and time!

**Comment by jonbarker68** [comment]
Thank you for raising these questions
1. Yes, there is a 5-ms latency limitation for CEC2 and we will be stricter about checking. 
2. If external training data is used we will ask for two submissions for the HASPI testing. The capacity of the listening panel is limited so we will only ask for one entry for listening test evaluation - this may be a system that has used external data.
3. ch0 (eardrum) is available in the train and dev data but will not be available in the evaluation data and should not be used as a system input. The hearing aid algorithm should only be using the hearing aid inputs CH1, CH2 and CH3.

If you have any further questions about the challenge please post them on the google group. https://groups.google.com/g/clarity-challenge
