### ISSUE TITLE
Include HASQI index

### ISSUE THREAD

**Issue by groadabike** [claritychallenge/clarity#91]
Migrate HASQI index from Matlab

**Comment by groadabike** [comment]
@jonbarker68 Maybe we need to refractor HASPI and HAAQI before including HASQI?

1- In Haspi implementation, the haspi/eb,py contains several of the supporting methods
2- In Haaqi implementation, the haspi/eb,py was extended with the haaqi methods as both methods share the EarModel method.

There are common methods and methods specific to each metric.
Is it possible to group all these metrics, 
For example, create evaluators/ha_metrics/*
and have:
* **ha_metrics/metrics.py**
Define haaqi, haspi and hasqi

* **ha_metrics/eb_haaqi.py**
* **ha_metrics/eb_haspi.py**
* **ha_metrics/eb_hasqi.py**
* **ha_metrics/utils.py**
Here include the common methods


Perhaps, a better thing would be to change the HA_metrics into class with each metric extending from an abstract class but this may be a mayor change

**Comment by jwillbailey** [comment]
Hi Gerado, 

Is the HASQI implementation in branch 91-include-hasqi-index ready?

Will
