### ISSUE TITLE
In enhancer.nalr.build, make parameter cfs as None by default

### ISSUE THREAD

**Issue by groadabike** [claritychallenge/clarity#93]
Matlab version of NALR has 3 parameters, **HL, nfir, fs**
```
function [nalr,delay]=eb_NALR(HL,nfir,fsamp)
```
In Clarity, NALR is implemented as a Class in enhancer.nalr.
```
class NALR:
    def __init__(self, nfir, fs):
        [...]
    def hl_interp(self, hl, cfs):
        [...]
    def build(self, HL, cfs):
        HL = self.hl_interp(np.array(HL), np.array(cfs))
        [...]
```

For the cases when cfs is not available and to match MATLAB's use of HAAQI and HASQI, it is needed to make **cfs=None** and add the if conditional
```
def build(self, HL, cfs=None):
    if not cfs is None:
         HL = self.hl_interp(np.array(HL), np.array(cfs))
    [...]
```

**Comment by groadabike** [comment]
Instead of 
```
def build(self, HL, cfs=None):
    if not cfs is None:
         HL = self.hl_interp(np.array(HL), np.array(cfs))
    [...]
```
it will be changed as
```
def build(self, HL, cfs=None):
    if cfs is None:
         cfs = [250, 500, 1000, 2000, 4000, 6000]
    [...]
```

**Comment by groadabike** [comment]
@TuZehai Does NALR CLass need to use the custom firwin2?
At this point, shouldn't be better to adopt to Scipy implementation?

**Comment by TuZehai** [comment]
I can not quite remember the detail now... I imagine the difference should be very minor?

**Comment by groadabike** [comment]
I will PR this minor change first as I need it to continue migrating HASQI.
Then we can come back and check the fir2 and firwin2
