### ISSUE TITLE
Add py as requirement for test 

### ISSUE THREAD

**Issue by groadabike** [claritychallenge/clarity#95]
PR test failing due to [py](https://pypi.org/project/py/) is no longer being pulled in and installed as a required dependency of pytest-regtest. (related to this issue in pytest-regtest https://gitlab.com/uweschmitt/pytest-regtest/-/issues/19)

**Comment by ns-rse** [comment]
As noted in the [comment](https://gitlab.com/uweschmitt/pytest-regtest/-/issues/19#note_1149994426) on the GitLab issue it is `pytest-7.2` that has [depcrecated `py` dependency](https://docs.pytest.org/en/stable/changelog.html#deprecations) (see also [PR 10936](https://github.com/pytest-dev/pytest/pull/10396)).

I guess unless/until `pytest-regtest` includes this as a dependency we will have to retain it as a dependency here under `tests`.
